import random
num1 = random.randint(1, 60)
num2 = random.randint(1, 60)
num3 = random.randint(1, 60)
num4 = random.randint(1, 60)
num5 = random.randint(1, 60)
num6 = random.randint(1, 60)
num1loto = random.randint(1, 25)
num2loto = random.randint(1, 25)
num3loto = random.randint(1, 25)
num4loto = random.randint(1, 25)
num5loto = random.randint(1, 25)
num6loto = random.randint(1, 25)
num7loto = random.randint(1, 25)
num8loto = random.randint(1, 25)
num9loto = random.randint(1, 25)
num10loto = random.randint(1, 25)
num11loto = random.randint(1, 25)
num12loto = random.randint(1, 25)
num13loto = random.randint(1, 25)
num14loto = random.randint(1, 25)
num15loto = random.randint(1, 25)
num1quina = random.randint(1, 80)
num2quina = random.randint(1, 80)
num3quina = random.randint(1, 80)
num4quina = random.randint(1, 80)
num5quina = random.randint(1, 80)
num0lotomania = random.randint(0, 99)
num1lotomania = random.randint(0, 99)
num2lotomania = random.randint(0, 99)
num2lotomania = random.randint(0, 99)
num3lotomania = random.randint(0, 99)
num4lotomania = random.randint(0, 99)
num5lotomania = random.randint(0, 99)
num6lotomania = random.randint(0, 99)
num7lotomania = random.randint(0, 99)
num8lotomania = random.randint(0, 99)
num9lotomania = random.randint(0, 99)
num10lotomania = random.randint(0, 99)
num11lotomania = random.randint(0, 99)
num12lotomania = random.randint(0, 99)
num13lotomania = random.randint(0, 99)
num14lotomania = random.randint(0, 99)
num15lotomania = random.randint(0, 99)
num16lotomania = random.randint(0, 99)
num17lotomania = random.randint(0, 99)
num18lotomania = random.randint(0, 99)
num19lotomania = random.randint(0, 99)
num20lotomania = random.randint(0, 99)
num1timemania = random.randint(1, 80)
num2timemania = random.randint(1, 80)
num3timemania = random.randint(1, 80)
num4timemania = random.randint(1, 80)
num5timemania = random.randint(1, 80)
num6timemania = random.randint(1, 80)
num7timemania = random.randint(1, 80)
num1duplasena = random.randint(1, 50)
num2duplasena = random.randint(1, 50)
num3duplasena = random.randint(1, 50)
num4duplasena = random.randint(1, 50)
num5duplasena = random.randint(1, 50)
num6duplasena = random.randint(1, 50)
num1duplasena2 = random.randint(1, 50)
num2duplasena2 = random.randint(1, 50)
num3duplasena2 = random.randint(1, 50)
num4duplasena2 = random.randint(1, 50)
num5duplasena2 = random.randint(1, 50)
num6duplasena2 = random.randint(1, 50)
linha = 126 * "-"
print(linha)
print("Seis números aleatórios para o jogo da Mega-Sena : {}, {}, {}, {}, {}, {}".format(num1, num2, num3, num4, num5, num6))
print(linha)
print("Quinze números aleatórios para o jogo da Lotofácil : {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}".format(num1loto, num2loto, num3loto, num4loto, num5loto, num6loto, num7loto, num8loto, num9loto, num10loto, num11loto, num12loto, num13loto, num14loto, num15loto))
print(linha)
print("Cinco números aleatórios para o jogo da Quina : {}, {}, {}, {}, {}".format(num1quina, num2quina, num3quina, num4quina, num5quina))
print(linha)
print("Vinte números aleatórios para o jogo da Lotomania : {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {} ".format(num0lotomania, num1lotomania, num2lotomania, num3lotomania, num4lotomania, num5lotomania, num6lotomania, num7lotomania, num8lotomania, num9lotomania, num10lotomania, num11lotomania, num12lotomania, num13lotomania, num14lotomania, num15lotomania, num16lotomania, num17lotomania, num18lotomania, num19lotomania, num20lotomania))
print(linha)
print("Sete números aleatórios para o jogo da Timemania : {}, {}, {}, {}, {}, {}, {} ".format(num1timemania, num2timemania, num3timemania, num4timemania, num5timemania, num6timemania, num7timemania))
print(linha)
print("Seis números aleatórios para o 1º jogo da Duplasena : {}, {}, {}, {}, {}, {} ".format(num1duplasena, num2duplasena, num3duplasena, num4duplasena, num5duplasena, num6duplasena))
print("Seis números aleatórios para o 2º jogo da Duplasena : {}, {}, {}, {}, {}, {} ".format(num1duplasena2, num2duplasena2, num3duplasena2, num4duplasena2, num5duplasena2, num6duplasena2))
